// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: coffee_shop.proto

package coffeeshop

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeeShopService_GetMenu_FullMethodName        = "/coffee_shop.CoffeeShopService/GetMenu"
	CoffeeShopService_PlaceOrder_FullMethodName     = "/coffee_shop.CoffeeShopService/PlaceOrder"
	CoffeeShopService_GetOrderStatus_FullMethodName = "/coffee_shop.CoffeeShopService/GetOrderStatus"
)

// CoffeeShopServiceClient is the client API for CoffeeShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoffeeShopServiceClient interface {
	GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MenuResponse], error)
	PlaceOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*Receipt, error)
	GetOrderStatus(ctx context.Context, in *Receipt, opts ...grpc.CallOption) (*OrderStatus, error)
}

type coffeeShopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeShopServiceClient(cc grpc.ClientConnInterface) CoffeeShopServiceClient {
	return &coffeeShopServiceClient{cc}
}

func (c *coffeeShopServiceClient) GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MenuResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoffeeShopService_ServiceDesc.Streams[0], CoffeeShopService_GetMenu_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MenuRequest, MenuResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShopService_GetMenuClient = grpc.ServerStreamingClient[MenuResponse]

func (c *coffeeShopServiceClient) PlaceOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, CoffeeShopService_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeShopServiceClient) GetOrderStatus(ctx context.Context, in *Receipt, opts ...grpc.CallOption) (*OrderStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, CoffeeShopService_GetOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoffeeShopServiceServer is the server API for CoffeeShopService service.
// All implementations must embed UnimplementedCoffeeShopServiceServer
// for forward compatibility.
type CoffeeShopServiceServer interface {
	GetMenu(*MenuRequest, grpc.ServerStreamingServer[MenuResponse]) error
	PlaceOrder(context.Context, *OrderRequest) (*Receipt, error)
	GetOrderStatus(context.Context, *Receipt) (*OrderStatus, error)
	mustEmbedUnimplementedCoffeeShopServiceServer()
}

// UnimplementedCoffeeShopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeShopServiceServer struct{}

func (UnimplementedCoffeeShopServiceServer) GetMenu(*MenuRequest, grpc.ServerStreamingServer[MenuResponse]) error {
	return status.Error(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedCoffeeShopServiceServer) PlaceOrder(context.Context, *OrderRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedCoffeeShopServiceServer) GetOrderStatus(context.Context, *Receipt) (*OrderStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderStatus not implemented")
}
func (UnimplementedCoffeeShopServiceServer) mustEmbedUnimplementedCoffeeShopServiceServer() {}
func (UnimplementedCoffeeShopServiceServer) testEmbeddedByValue()                           {}

// UnsafeCoffeeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeShopServiceServer will
// result in compilation errors.
type UnsafeCoffeeShopServiceServer interface {
	mustEmbedUnimplementedCoffeeShopServiceServer()
}

func RegisterCoffeeShopServiceServer(s grpc.ServiceRegistrar, srv CoffeeShopServiceServer) {
	// If the following call panics, it indicates UnimplementedCoffeeShopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeeShopService_ServiceDesc, srv)
}

func _CoffeeShopService_GetMenu_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MenuRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoffeeShopServiceServer).GetMenu(m, &grpc.GenericServerStream[MenuRequest, MenuResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeShopService_GetMenuServer = grpc.ServerStreamingServer[MenuResponse]

func _CoffeeShopService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeShopServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeShopService_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeShopServiceServer).PlaceOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeShopService_GetOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Receipt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeShopServiceServer).GetOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeShopService_GetOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeShopServiceServer).GetOrderStatus(ctx, req.(*Receipt))
	}
	return interceptor(ctx, in, info, handler)
}

// CoffeeShopService_ServiceDesc is the grpc.ServiceDesc for CoffeeShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeeShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coffee_shop.CoffeeShopService",
	HandlerType: (*CoffeeShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _CoffeeShopService_PlaceOrder_Handler,
		},
		{
			MethodName: "GetOrderStatus",
			Handler:    _CoffeeShopService_GetOrderStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMenu",
			Handler:       _CoffeeShopService_GetMenu_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coffee_shop.proto",
}
